version: '3.2'

networks:
  net:

services:

  solr:
    image: vivoweb/vivo-solr:latest
    hostname: solr
    environment:
      - RESET_CORE=${RESET_CORE}
      - VERBOSE=${VERBOSE}
    ports:
      - 8983:8983
    volumes:
      - ${LOCAL_SOLR_DATA}:/opt/solr/server/solr/mycores
    networks:
      - net

  tomcat:
    container_name: vivo
    hostname: vivo
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - RESET_HOME=${RESET_HOME}
      - VERBOSE=${VERBOSE}
      - SOLR_URL=http://solr:8983/solr/vivocore
    ports:
      - 8080:8080
    volumes:
      - ${LOCAL_VIVO_HOME}:/opt/vivo/home
    depends_on:
      - solr
    networks:
      - net
