version: '3.2'

networks:
  net:

services:

  solr:
    image: vivoweb/vivo-solr:latest
    hostname: solr
    environment:
      - VERBOSE=${VERBOSE}
      - RESET_CORE=true
    ports:
      - 8983:8983
    volumes:
      - ${LOCAL_SOLR_DATA}:/opt/solr/server/solr/mycores
    networks:
      - net

  tomcat:
    container_name: vivo
    hostname: vivo
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - VERBOSE=${VERBOSE}
      - RESET_HOME=true
      - SOLR_URL=http://solr:8983/solr/vivocore
      - LANGUAGE_FILTER_ENABLED=true
      - SELECTABLE_LOCALES=en_US,de_DE,sr_Latn_RS,ru_RU,fr_CA,en_CA,es,pt_BR
      - LOAD_SAMPLE_DATA=true
      - SAMPLE_DATA_REPO_URL=https://github.com/chenejac/sample-data.git
      - SAMPLE_DATA_BRANCH=reorganization
      - SAMPLE_DATA_DIRECTORY=i18n
    ports:
      - 8080:8080
    volumes:
      - ${LOCAL_VIVO_HOME}:/usr/local/vivo/home
    depends_on:
      - solr
    networks:
      - net
    entrypoint:
      - /bin/bash
      - '-c'
      - |
        while (!</dev/tcp/solr/8983) > /dev/null 2>&1; do sleep 1; done;
        sleep 5
        /start.sh
